name:                     Linters

on:                       pull_request

env:
  FORCE_COLOR:            1

jobs:
  rubocop:
    name:                 Rubocop
    runs-on:              ubuntu-latest
    steps:
      - uses:             actions/checkout@v2
      - uses:             ruby/setup-ruby@v1
        with:
          bundler-cache:  true
      - name:             Setup Rubocop
        run:              |
          [ -f .rubocop.yml ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ruby/.rubocop.yml
      - name:             Rubocop Report
        run:              bundle exec rubocop --color
  stylelint:
    name:                 StyleLint
    runs-on:              ubuntu-latest
    steps:
      - uses:             actions/checkout@v2
      - uses:             actions/setup-node@v2
        with:
            node-version: 14
            check-latest: true
      - name:             Setup Stylelint
        run:              |
          npm install --save-dev stylelint stylelint-config-sass-guidelines
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/ror/.stylelintrc.json
      - name:             Stylelint Report
        run:              npx stylelint "**/*.{css,scss}"
